{% set name = "ciso8601" %}
{% set version = "2.1.2" %}
{% set sha256 = "307342e8bb362ae41a3f3a089c11b374116823bce6fbe5d784e2a2dc37f2c753" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - ciso8601

about:
  home: https://github.com/closeio/ciso8601
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Fast ISO8601 date time parser for Python written in C'

  description: |
    ciso8601 converts ISO8601 date time strings into Python datetime objects.
  dev_url: https://github.com/closeio/ciso8601

extra:
  recipe-maintainers:
    - synapticarbors
