{% set name = "ciso8601" %}
{% set version = "1.0.8" %}
{% set sha256 = "9530790a7b4eeefdec77970966acec0c6fdfd7a4ea1a78ac470b671f98622586" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - toolchain
  run:
    - python

test:
  imports:
    - ciso8601

about:
  home: https://github.com/closeio/ciso8601
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Fast ISO8601 date time parser for Python written in C'

  description: |
    ciso8601 converts ISO8601 date time strings into Python datetime objects.
  dev_url: https://github.com/closeio/ciso8601

extra:
  recipe-maintainers:
    - synapticarbors
