travis:
  secure:
    BINSTAR_TOKEN: dskKYK7I9cY8DVlayFzIYyxj9OYrF/yVYaj8su7iFOEv21yshDeXNCLE4kS6z6OAMuTCK0+UhIciFdm0BwjHvLGmY+vI8NRFbVCHv3vCZmApXQp1bsO4GH6a5XI/hDLaZBRGYoUhOPLbxuRgh5YHJAsYv0KHNHIlOrYgyWJIUr0isC7zRE2rvYwcRVfbYQ3ooL8p+Frmmj0EfrVz225ufD0QeEi2t7qpzNH//n3cioF2aRlLvdFVCGrQL3k/sb1tSo+qyp6hVGB08cV6fGCmLt0rxrJr6QLpUUabrC6l53pRXAOjAK6cXYTXRFWj/tVGDm+Oa0YGqUh0Wcl1Pw1uBsWAqs5m5+6PHFgQk2MucFKxisDXScmauVypRJ2GDKG0UHXYW+M4BLQE7NnhDTFA48E2yMKMnPb2tXP4vSl+GDFrZq2gvYvWaGHaEHjiAq1b7qKnZ3iOfdPu/sZcrBYGihbC7qcX1qr5mgZewU42dRz3grv6vCTBIDDcMxKhnLNRAmqp8/E0SVPjLSyL8pFSCWBHGB8MbyHSwxujl17upEXuL8AOzSJBcf+Fd6bifeljQ51ni87JvwEcjNcF3J7Yzxpitp15cVPFrFnngk5UhoM52MYYdJWqj2EFL1ySAiQU5ZfX+ABsxOOAUwI21WxXUPScmkWmSnKz+QKfPYqAFKg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
