appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: VRlY/uks36XMjr53pw5D9L9hI5fn/Z2xBYzYVaCGs2PasIAMXxCjfoBV3MZL31tzHUqiLAr0JjambC/bplJLsqFb0z06gDhEVaIP/aRfef9CGksCKUSmK/oEU7vxdz6TSBoZqq+bn/G66+CpqgDVgomueHfemFnlapGnNlYL+wzkmlq+EafLa2r+K7+NCSQ0otKruqxpmYeRaEYMilrUCtbN2jxbqwPJMLfskiRAkj4JT0Tj8jwxEyZKXdeOCxVPTyvGEEd45VZE0HDerfsjQc4dBpJeJBDvr2lLXsdvmyiuz+4QTX9KRKiW3Y3lpNxCxlgzjWMOaGuqPzPB6KOX+imcgKPVzh1EPxoRVMzv5UlT+OBZLpkqETt78kNzMD4fIvYUc1XAvCCS/obwNmyYjQBZG6QU9ba8ySUWiheO56z08xGF1G98m9DC7n8FsmQTtYiEgilt037pkRBoOPfAvJzYmg3pCzPXagJkBTU0uRAtqfujMjAIIOiappTH6tK2tFJdHD2V4Sz/aX2kfHuv6vKcMF6Ey+92El0OO3crsXDA4yikV81z8u0ImTLq15k5M3CVdPU3cwNcFfheyufK+resp2GS9S1Q55DWJxJkRT01fzJgJQjcWHNfVuDJc6J7dqLeXY4AbwQqU8cWsa09QlTLvKWXIIAEFvPhJ9l4csc=}
