travis:
  secure:
    BINSTAR_TOKEN: YtrR8IUTNxgMDCX2cYER0ReVjlB6uzqiDfOcM4u/bSDJzLWvrIWotYlfztxCXL8azbLXyc0gq73Sz6MQ0Asm+hDsGaLrl+X95Py7s8X20g/3mtFgT4imJQuB7OLLX3iyBIEmxaUobW/essWwBICknminWaQfOskKAYeEUkohLFvv/b+UbAzLouVDAoxjjoWaLBC/ViB5C+FQG+8t5hFLsADjLj9dxIeav0X6RqWz1cNKq8Eey3Q+xTLEo+wLa7iIslLzY1U5cLDY0sdz7Kx6DDk5cr7c/6NQuwRiq1YOFrHFB/xdKa+u+rn3SJLr9bJHMlnv27wuLzP9E0Sh9zytob5RYBvy59q7HirCwOE9pq+JbIyERN7CGg/nLUz641a5FpYrH9V/8J3a9U5qifGq3ViRQynMyBrMFrvvQM6Ek5X56iyBH05qSpPpGFWTjt0GVosEWeZWKD3aOXmRPRpLl2yw++2BJRE6gPRQjb4Z5iKETjadIfJJjI0gi6kgsBcvVVz+YMpmbApvWl5+/XyQnMJ0U+jrHwJDSMMc1yeKiEUzyCaerMx9eySr5A3twmSnNgqdIpuvG51CsrarkJZZ6YiP5mUoSmetjDeSI2twW28GMd+tp44u/ekLhzdhGfmBbhupNGN5Ux1NZLX4FCgTPtzJ/hCFi8DusogpUZRJDKs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
